/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/9.0.22 (8.0.0)
 * Generated at: 2020-05-06 15:27:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>FET AQUI</title>\n");
      out.write("<!--  FONT AWESOME -->\n");
      out.write("<!-- Font Awesome -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.2/css/all.css\">\n");
      out.write("<!-- Google Fonts -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\">\n");
      out.write("<!-- Bootstrap core CSS -->\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<!-- Material Design Bootstrap -->\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"css/estilos.css\" type=\"text/css\" rel=\"stylesheet\">\n");
      out.write("<!-- -------------------SCRIPTS--------------- -->\n");
      out.write("<!-- JQuery -->\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<!-- Bootstrap tooltips -->\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js\"></script>\n");
      out.write("<!-- Bootstrap core JavaScript -->\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js\"></script>\n");
      out.write("<!-- MDB core JavaScript -->\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js\"></script>\n");
      out.write("<script src=\"js/validarPassword.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div id=\"container\" style=\"min-height: 80vh\">\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-md bg-dark navbar-dark sticky-top\">\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#\">FET AQUÍ</a>\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\tdata-target=\"#collapsibleNavbar\">\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav\">\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"Principal\">Inicio</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"ObtenerTodosProductos\">Productos</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"ObtenerTodosVendedores\">Vendedores</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto nav-flex-icons\">\n");
      out.write("\t\t\t\t\t");

						if (request.getAttribute("error") != null) {
							String error = (String) request.getAttribute("error");
					
      out.write("\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"btn btn-danger btn-sm\"\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#\">");
      out.print(error);
      out.write("</a></li>\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"btn btn-primary btn-sm\"\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#modalRegistro\">REGISTRARSE</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"btn btn-success btn-sm\"\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#modalLogin\">LOGIN</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<li class=\"nav-item avatar\"><a class=\"nav-link p-0\" href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/user.png\" class=\"rounded-circle z-depth-0\"\n");
      out.write("\t\t\t\t\t\t\talt=\"avatar image\" height=\"35\">\n");
      out.write("\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t<!------------------------------------------------------MODAL DE ELECCION DE TIPO DE REGISTRO------------------------------------------------------------------------>\n");
      out.write("\t\t<div class=\"modal fade\" id=\"modalRegistro\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title\">¿Eres un profesional o un consumidor?</h4>\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"modal-body panelEleccionRegistro\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary btn-lg\" data-toggle=\"modal\"\n");
      out.write("\t\t\t\t\t\t\tdata-target=\"#formularioProfesional\">Profesional</button>\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-success btn-lg\" data-toggle=\"modal\"\n");
      out.write("\t\t\t\t\t\t\tdata-target=\"#formularioConsumidor\">Consumidor</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Cerrar</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!------------------------------------------------------MODAL DE REGISTRO DE PROFESIONAL------------------------------------------------------------------------>\n");
      out.write("\t\t<div class=\"modal fade\" id=\"formularioProfesional\" tabindex=\"-1\"\n");
      out.write("\t\t\trole=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header text-center\">\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title w-100 font-weight-bold\">Registrarse\n");
      out.write("\t\t\t\t\t\t\tcomo vendedor</h4>\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<form action=\"Principal\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body mx-3\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form mb-5\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-user prefix grey-text\"></i> <input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"orangeForm-name\" class=\"form-control validate\"\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"nombrep\"> <label data-error=\"wrong\"\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-success=\"right\" for=\"orangeForm-name\">Su nombre</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form mb-5\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-envelope prefix grey-text\"></i> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"email\" id=\"orangeForm-email\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control validate\" name=\"emailp\"> <label\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-error=\"wrong\" data-success=\"right\" for=\"orangeForm-email\">Su\n");
      out.write("\t\t\t\t\t\t\t\t\temail</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row my-5\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"md-form\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-lock prefix\"></i> <input type=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"inputValidationEx2\" class=\"form-control validate\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"passwordp\"> <label for=\"inputValidationEx2\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-error=\"Escriba su contraseña correctamente\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-success=\"OK\" style=\"width: 200px;\">Password</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-5\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"alert alert-warning password-alert\" role=\"alert\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"requirements leng\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-check green-text\"></i><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-times red-text\"></i> 8 caracteres</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"requirements big-letter\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-check green-text\"></i><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-times red-text\"></i> 1 letra mayúscula</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"requirements num\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-check green-text\"></i><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-times red-text\"></i> 1 número</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"requirements special-char\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-check green-text\"></i><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-times red-text\"></i> 1 carácter especial</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer d-flex justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t<button id=\"registrarse\" type=\"submit\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-deep-orange\" disabled>Registrarse</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!------------------------------------------------------MODAL DE REGISTRO DE CLIENTE------------------------------------------------------------------------>\n");
      out.write("\t\t<div class=\"modal fade\" id=\"formularioConsumidor\" tabindex=\"-1\"\n");
      out.write("\t\t\trole=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header text-center\">\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title w-100 font-weight-bold\">Registrarse\n");
      out.write("\t\t\t\t\t\t\tcomo cliente</h4>\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<form action=\"Principal\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body mx-3\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form mb-5\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-user prefix grey-text\"></i> <input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"orangeForm-name2\" class=\"form-control validate\"\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"nombrec\"> <label data-error=\"wrong\"\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-success=\"right\" for=\"orangeForm-name2\">Su nombre</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form mb-5\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-envelope prefix grey-text\"></i> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"email\" id=\"orangeForm-email2\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control validate\" name=\"emailc\"> <label\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-error=\"wrong\" data-success=\"right\" for=\"orangeForm-email2\">Su\n");
      out.write("\t\t\t\t\t\t\t\t\temail</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row my-5\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"md-form\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fas fa-lock prefix\"></i> <input type=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"inputValidationEx3\" class=\"form-control validate\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"passwordc\"> <label for=\"inputValidationEx3\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-error=\"Escriba su contraseña correctamente\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-success=\"OK\" style=\"width: 200px;\">Password</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-5\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"alert alert-warning password-alert\" role=\"alert\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"requirements leng\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-check green-text\"></i><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-times red-text\"></i> 8 caracteres</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"requirements big-letter\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-check green-text\"></i><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-times red-text\"></i> 1 letra mayúscula</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"requirements num\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-check green-text\"></i><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-times red-text\"></i> 1 número</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"requirements special-char\"><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-check green-text\"></i><i\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fas fa-times red-text\"></i> 1 carácter especial</li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer d-flex justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t<button id=\"registrarse2\" type=\"submit\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-deep-orange\" disabled>Registrarse</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- MODAL DE LOGIN -->\n");
      out.write("\n");
      out.write("\t\t<div class=\"modal fade\" id=\"modalLogin\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("\t\t\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t\t<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-header text-center\">\n");
      out.write("\t\t\t\t\t\t<h4 class=\"modal-title w-100 font-weight-bold\">ENTRAR</h4>\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<form action=\"Login\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body mx-3\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form mb-5\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-envelope prefix grey-text\"></i> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"email\" id=\"defaultForm-email\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control validate\" name=\"email\"> <label\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-error=\"wrong\" data-success=\"right\" for=\"defaultForm-email\">Email</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"md-form mb-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-lock prefix grey-text\"></i> <input\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"password\" id=\"defaultForm-pass\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control validate\" name=\"password\"> <label\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-error=\"wrong\" data-success=\"right\" for=\"defaultForm-pass\">Password</label>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer d-flex justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\">Login</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<!-- MODAL DE CONFIRMACIÓN DE EMAIL -->\n");
      out.write("\t\t<div class=\"modal fade\" id=\"centralModalSuccess\" tabindex=\"-1\"\n");
      out.write("\t\t\trole=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t\t<div class=\"modal-dialog modal-notify modal-success\" role=\"document\">\n");
      out.write("\t\t\t\t<!--Content-->\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<!--Header-->\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t<p class=\"heading lead\">¡Muchas gracias!</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\" class=\"white-text\">&times;</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!--Body-->\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t\t<div class=\"text-center\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-check fa-4x mb-3 animated rotateIn\"></i>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\tHa activado su usuario.<br> Recuerde que su usuario es el <strong>correo\n");
      out.write("\t\t\t\t\t\t\t\t\telectrónico</strong> con el que se ha registrado.\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!--Footer-->\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer justify-content-center\">\n");
      out.write("\t\t\t\t\t\t<a type=\"button\" class=\"btn btn-success\">Login <i\n");
      out.write("\t\t\t\t\t\t\tclass=\"fas fa-sign-in-alt\"></i></a> <a type=\"button\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-outline-success waves-effect\" data-dismiss=\"modal\">Cerrar</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!--/.Content-->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t");

			boolean activado = false;
			if (request.getAttribute("activado") != null) {
				activado = (boolean) request.getAttribute("activado");
			}

			String email = "";
			if (request.getAttribute("email") != null) {
				email = (String) request.getAttribute("email");
			}
		
      out.write("\n");
      out.write("\n");
      out.write("\t\t");

			if (activado == true) {
		
      out.write("\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\t$(document).ready(function() {\n");
      out.write("\t\t\t\t$(\"#centralModalSuccess\").modal('show');\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("\t\t");

			}
		
      out.write("\n");
      out.write("\n");
      out.write("\t\t");

			if (!email.equals("")) {
		
      out.write("\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\t$(document).ready(function() {\n");
      out.write("\t\t\t\t$(\"#centralModalInfo\").modal('show');\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("\t\t");

			}
		
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- Central Modal Medium Info -->\n");
      out.write("\t\t<div class=\"modal fade\" id=\"centralModalInfo\" tabindex=\"-1\"\n");
      out.write("\t\t\trole=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t\t<div class=\"modal-dialog modal-notify modal-info\" role=\"document\">\n");
      out.write("\t\t\t\t<!--Content-->\n");
      out.write("\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t<!--Header-->\n");
      out.write("\t\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t\t<p class=\"heading lead\">Información importante</p>\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\t\taria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t\t<span aria-hidden=\"true\" class=\"white-text\">&times;</span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!--Body-->\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t\t<div class=\"text-center\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-check fa-4x mb-3 animated rotateIn\"></i>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\tLe hemos enviado un correo electrónico para confirmar su\n");
      out.write("\t\t\t\t\t\t\t\tusuario. <br> Haga click sobre el enlace que le hemos\n");
      out.write("\t\t\t\t\t\t\t\tenviado para activarlo\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!--Footer-->\n");
      out.write("\t\t\t\t\t<div class=\"modal-footer justify-content-center\">\n");
      out.write("\t\t\t\t\t\t<a type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">Entendido</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!--/.Content-->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- Footer -->\n");
      out.write("\t<footer class=\"page-footer font-small unique-color-dark pt-4\">\n");
      out.write("\n");
      out.write("\t\t<!-- Footer Elements -->\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- Call to action -->\n");
      out.write("\t\t\t<ul class=\"list-unstyled list-inline text-center py-2\">\n");
      out.write("\t\t\t\t<li class=\"list-inline-item\">\n");
      out.write("\t\t\t\t\t<h5 class=\"mb-1\">Regístrate gratis!</h5>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<li class=\"list-inline-item\"><a href=\"Login\"\n");
      out.write("\t\t\t\t\tclass=\"btn btn-outline-white btn-rounded\" data-toggle=\"modal\"\n");
      out.write("\t\t\t\t\tdata-target=\"#modalRegistro\">Darse de alta</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<!-- Call to action -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- Footer Elements -->\n");
      out.write("\n");
      out.write("\t\t<!-- Copyright -->\n");
      out.write("\t\t<div class=\"footer-copyright text-center py-3 \">\n");
      out.write("\t\t\t© 2020 Copyright: <a href=\"https://fetaqui.com/\"> fetaqui.com</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- Copyright -->\n");
      out.write("\n");
      out.write("\t</footer>\n");
      out.write("\t<!-- Footer -->\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
