/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/9.0.22 (8.0.0)
 * Generated at: 2020-05-06 15:28:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import modelo.pojo.Producto;
import modelo.pojo.Vendedor;
import modelo.pojo.Categoria;
import java.util.ArrayList;

public final class PaginaPropiaVendedor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("modelo.pojo.Producto");
    _jspx_imports_classes.add("modelo.pojo.Vendedor");
    _jspx_imports_classes.add("modelo.pojo.Categoria");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>FET AQUI</title>\n");
      out.write("<!-- Font Awesome -->\n");
      out.write("<base href=\"/\"> \n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.2/css/all.css\">\n");
      out.write("<!-- Google Fonts -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\">\n");
      out.write("<!-- Bootstrap core CSS -->\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<!-- Material Design Bootstrap -->\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"css/estilos.css\" type=\"text/css\" rel=\"stylesheet\">\n");
      out.write("<!-- -------------------SCRIPTS--------------- -->\n");
      out.write("<!-- JQuery -->\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<!-- Bootstrap tooltips -->\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js\"></script>\n");
      out.write("<!-- Bootstrap core JavaScript -->\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js\"></script>\n");
      out.write("<!-- MDB core JavaScript -->\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js\"></script>\n");
      out.write("<script src=\"js/validarPassword.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write(" \n");
      out.write("    ");

        ArrayList<Categoria> categorias = null;
        ArrayList<Producto> productos = null;
        Categoria categoria = null;
        Vendedor vendedor = null;
 
        if (request.getAttribute("categorias") != null) {
            categorias = (ArrayList<Categoria>) request.getAttribute("categorias");
        }
 
        if (request.getAttribute("productos") != null) {
            productos = (ArrayList<Producto>) request.getAttribute("productos");
        }
 
        if (request.getAttribute("categoria") != null) {
 
            categoria = (Categoria) request.getAttribute("categoria");
        }
 
        if (request.getAttribute("vendedor") != null) {
 
            vendedor = (Vendedor) request.getAttribute("vendedor");
        }
    
      out.write("\n");
      out.write(" \n");
      out.write("    <div id=\"container\" style=\"min-height: 80vh\">\n");
      out.write(" \n");
      out.write("        <!-- NAVEGADOR -->\n");
      out.write("        <nav class=\"navbar navbar-expand-md bg-dark navbar-dark sticky-top\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">FET AQUÍ</a>\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("                data-target=\"#collapsibleNavbar\">\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\n");
      out.write("                <ul class=\"navbar-nav\">\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"Principal\">Inicio</a></li>\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"Productos\">Productos</a></li>\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"ObtenerTodosVendedores\">Vendedores</a></li>\n");
      out.write("                </ul>\n");
      out.write("                \n");
      out.write("                <ul class=\"navbar-nav ml-auto nav-flex-icons\">\n");
      out.write("                <li class=\"nav-item\"><a class=\"btn btn-primary btn-sm\"\n");
      out.write("                        href=\"PaginaPropioVendedor\">MI PÁGINA</a></li>\n");
      out.write("                    <li class=\"nav-item\"><a class=\"btn btn-primary btn-sm\"\n");
      out.write("                        href=\"OpcionesPerfilVendedor.jsp\">ADMINISTRACIÓN</a></li>\n");
      out.write("                    <li class=\"nav-item\"><a class=\"btn btn-success btn-sm\"\n");
      out.write("                        href=\"Logout\">SALIR</a></li>\n");
      out.write("                    ");

                        if (vendedor.getFoto().equals("desconocido.txt")) {
                    
      out.write("\n");
      out.write("                    <li class=\"nav-item avatar\"><a class=\"nav-link p-0\"\n");
      out.write("                        href=\"OpcionesPerfilVendedor.jsp\"> <img src=\"img/user.png\"\n");
      out.write("                            class=\"rounded-circle z-depth-0\" alt=\"avatar image\" height=\"35\">\n");
      out.write("                    </a></li>\n");
      out.write("                    ");

                        } else {
                    
      out.write("\n");
      out.write("                    <li class=\"nav-item avatar\"><a class=\"nav-link p-0\"\n");
      out.write("                        href=\"OpcionesPerfilVendedor.jsp\"> <img\n");
      out.write("                            src=\"Imagenes/");
      out.print(vendedor.getFoto());
      out.write("\"\n");
      out.write("                            class=\"rounded-circle z-depth-0\" alt=\"avatar image\" height=\"35\">\n");
      out.write("                    </a></li>\n");
      out.write("                    ");

                        }
                    
      out.write("\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <!-- FIN NAVEGADOR -->\n");
      out.write(" \n");
      out.write("        <!-- CONTENEDOR PRINCIPAL -->\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write(" \n");
      out.write("            <div class=\"row\">\n");
      out.write(" \n");
      out.write("                <div id=\"lateral\" class=\"col col-lg-2\">\n");
      out.write(" \n");
      out.write("                    <div>\n");
      out.write("                        <img id=\"imagenVendedor\" src=\"Imagenes/");
      out.print(vendedor.getFoto());
      out.write("\">\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div>\n");
      out.write("                        <h2>");
      out.print(vendedor.getNombre());
      out.write("</h2>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div>\n");
      out.write("                        <h4>LOCALIZACIÓN</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div>\n");
      out.write("                        <p>");
      out.print(vendedor.getPoblacion());
      out.write("</p>\n");
      out.write("                        <hr>\n");
      out.write("                        <p>");
      out.print(vendedor.getDireccion());
      out.write("</p>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <div>\n");
      out.write("                        <h4>CONTACTO</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <hr>\n");
      out.write("                    <p>");
      out.print(vendedor.getTelefono());
      out.write("</p>\n");
      out.write("                    <hr>\n");
      out.write("                    <p>");
      out.print(vendedor.getEmail());
      out.write("</p>\n");
      out.write("                    <hr>\n");
      out.write("                    <div>\n");
      out.write("                        <h4>¿VENDE ONLINE?</h4>\n");
      out.write("                        ");

                            if (vendedor.getVenta_online() == 1) {
                        
      out.write("\n");
      out.write("                        <h5>SI</h5>\n");
      out.write("                        ");

                            } else {
                        
      out.write("\n");
      out.write("                        <h5>NO</h5>\n");
      out.write("                        ");

                            }
                        
      out.write("\n");
      out.write("                    </div>\n");
      out.write(" \n");
      out.write(" \n");
      out.write(" \n");
      out.write("                </div>\n");
      out.write(" \n");
      out.write("                <div id=\"main\" class=\"col col-lg-8 text-center\">\n");
      out.write(" \n");
      out.write("                    <!-- DIV ELECCION CATEGORÍA -->\n");
      out.write("                    ");

                        if (categoria != null) {
                    
      out.write("\n");
      out.write(" \n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <!-- DIV BUSQUEDA POR CATEGORÍA -->\n");
      out.write("                        <div class=\"row\">\n");
      out.write(" \n");
      out.write("                            <div class=\"col col-lg-12 m-5 text-center\">\n");
      out.write("                                <h3>BUSCAR POR CATEGORÍAS</h3>\n");
      out.write("                                <form id=\"categorias\" action=\"PaginaPropioVendedor\"\n");
      out.write("                                    method=\"get\">\n");
      out.write("                                    <input type=\"hidden\" name=\"id_vendedor\" value=\"");
      out.print(vendedor.getId_vendedor() );
      out.write("\">\n");
      out.write("                                    <select name=\"selectCategorias\" id=\"selectCategorias\"\n");
      out.write("                                        class=\"browser-default custom-select\">\n");
      out.write("                                        \n");
      out.write("                                        <option value=\"");
      out.print(categoria.getId());
      out.write("\" selected>");
      out.print(categoria.getNombre());
      out.write("</option>\n");
      out.write("                                        <option value=\"todos\">TODOS LOS PRODUCTOS</option>\n");
      out.write("                                        ");

                                            for (Categoria ca : categorias) {
                                        
      out.write("\n");
      out.write("                                        <option value=");
      out.print(ca.getId());
      out.write(">\n");
      out.write("                                            ");
      out.print(ca.getNombre());
      out.write("</option>\n");
      out.write("                                        ");

                                            }
                                        
      out.write("\n");
      out.write("                                    </select>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write(" \n");
      out.write(" \n");
      out.write("                        </div>\n");
      out.write("                        <!-- FIN DIV BUSQUEDA POR CATEGORÍA -->\n");
      out.write("                    </div>\n");
      out.write("                    <!-- FIN DIV ELECCION CATEGORÍA -->\n");
      out.write(" \n");
      out.write("                    ");

                        } else {
                    
      out.write("\n");
      out.write(" \n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <!-- DIV BUSQUEDA POR CATEGORÍA -->\n");
      out.write("                        <div class=\"row\">\n");
      out.write(" \n");
      out.write("                            <div class=\"col col-lg-12 m-5 text-center\">\n");
      out.write("                                <h3>BUSCAR POR CATEGORÍAS</h3>\n");
      out.write("                                <form id=\"categorias\" action=\"PaginaPropioVendedor\"\n");
      out.write("                                    method=\"get\">\n");
      out.write("                                    <input type=\"hidden\" name=\"id_vendedor\" value=\"");
      out.print(vendedor.getId_vendedor() );
      out.write("\">\n");
      out.write("                                    <select name=\"selectCategorias\" id=\"selectCategorias\"\n");
      out.write("                                        class=\"browser-default custom-select\">\n");
      out.write("                                        <option value=\"todos\" selected>TODOS LOS PRODUCTOS</option>\n");
      out.write("                                        ");

                                            for (Categoria ca : categorias) {
                                        
      out.write("\n");
      out.write("                                        <option value=");
      out.print(ca.getId());
      out.write(">\n");
      out.write("                                            ");
      out.print(ca.getNombre());
      out.write("</option>\n");
      out.write("                                        ");

                                            }
                                        
      out.write("\n");
      out.write("                                    </select>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write(" \n");
      out.write(" \n");
      out.write("                        </div>\n");
      out.write("                        <!-- FIN DIV BUSQUEDA POR CATEGORÍA -->\n");
      out.write("                    </div>\n");
      out.write("                    <!-- FIN DIV ELECCION CATEGORÍA -->\n");
      out.write(" \n");
      out.write("                    ");

                        }
                    
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("                    ");

                        if (request.getAttribute("error") != null) {
                            String error = (String) request.getAttribute("error");
                    
      out.write("\n");
      out.write(" \n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <!-- DIV ERROR-->\n");
      out.write("                        <div class=\"row\">\n");
      out.write(" \n");
      out.write("                            <div class=\"col col-lg-12 m-5 text-center\">\n");
      out.write("                                <h3>");
      out.print(error);
      out.write("</h3>\n");
      out.write("                            </div>\n");
      out.write(" \n");
      out.write(" \n");
      out.write("                        </div>\n");
      out.write("                        <!-- FIN DIV BUSQUEDA POR CATEGORÍA -->\n");
      out.write("                    </div>\n");
      out.write("                    <!-- FIN DIV ELECCION CATEGORÍA -->\n");
      out.write(" \n");
      out.write("                    ");

                        } else {
                    
      out.write("\n");
      out.write(" \n");
      out.write("                    <!-- Card deck -->\n");
      out.write("                    <div class=\"row row-cols-1 row-cols-md-5\">\n");
      out.write(" \n");
      out.write("                        ");

                            for (Producto pro : productos) {
                        
      out.write("\n");
      out.write(" \n");
      out.write(" \n");
      out.write("                        <!-- Card -->\n");
      out.write("                        <div class=\"col mb-4\">\n");
      out.write("                            <div class=\"card h-100\">\n");
      out.write("                                <!--Card image-->\n");
      out.write("                                <div id=\"contenedorImagenProducto\" class=\"view overlay zoom\">\n");
      out.write("                                    ");

                                        if (pro.getFoto().equals("producto.png")) {
                                    
      out.write("\n");
      out.write("                                    <img id=\"imagenProducto\" class=\"img-fluid z-depth-1\"\n");
      out.write("                                        src=\"img/");
      out.print(pro.getFoto());
      out.write("\" alt=\"Card image cap\">\n");
      out.write(" \n");
      out.write("                                    ");

                                        } else {
                                    
      out.write("\n");
      out.write("                                    <img id=\"imagenProducto\" class=\"img-fluid z-depth-1\"\n");
      out.write("                                        src=\"Imagenes/");
      out.print(pro.getFoto());
      out.write("\" alt=\"Card image cap\">\n");
      out.write("                                    ");

                                        }
                                    
      out.write("\n");
      out.write("                                    <div class=\"mask rgba-white-slight\"></div>\n");
      out.write("                                </div>\n");
      out.write(" \n");
      out.write("                                <!--Card content-->\n");
      out.write("                                <div class=\"card-body text-center\">\n");
      out.write(" \n");
      out.write("                                    <!--Title-->\n");
      out.write("                                    <h4 class=\"card-title\">");
      out.print(pro.getNombre());
      out.write("</h4>\n");
      out.write("                                    <!--Text-->\n");
      out.write("                                    <p id=\"descripcionProducto\" class=\"card-text\">");
      out.print(pro.getDescripcion());
      out.write("</p>\n");
      out.write("                                    <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->\n");
      out.write("                                    <div class=\"container\">\n");
      out.write("                                        <div class=\"row\">\n");
      out.write(" \n");
      out.write("                                            <div class=\"col col-lg-12 text-center\">\n");
      out.write("                                                <h5>Precio: ");
      out.print(pro.getPrecio());
      out.write("€ / ");
      out.print(pro.getFormato());
      out.write("</h5>\n");
      out.write("                                            </div>\n");
      out.write(" \n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write(" \n");
      out.write("                        ");

                            }
                        
      out.write("\n");
      out.write("                        ");

                            }
                        
      out.write("\n");
      out.write("                        <!-- Card -->\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Card deck -->\n");
      out.write(" \n");
      out.write("                </div>\n");
      out.write("            \t\n");
      out.write("            \t\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write(" \n");
      out.write("        <!------------------------------------------------------MODAL DE ELECCION DE TIPO DE REGISTRO------------------------------------------------------------------------>\n");
      out.write("        <div class=\"modal fade\" id=\"modalRegistro\" tabindex=\"-1\" role=\"dialog\">\n");
      out.write("            <div class=\"modal-dialog\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <h4 class=\"modal-title\">¿Eres un profesional o un consumidor?</h4>\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">×</button>\n");
      out.write("                    </div>\n");
      out.write(" \n");
      out.write(" \n");
      out.write("                    <div class=\"modal-body panelEleccionRegistro\">\n");
      out.write("                        <button class=\"btn btn-primary btn-lg\" data-toggle=\"modal\"\n");
      out.write("                            data-target=\"#formularioProfesional\">Profesional</button>\n");
      out.write("                        <button class=\"btn btn-success btn-lg\" data-toggle=\"modal\"\n");
      out.write("                            data-target=\"#formularioConsumidor\">Consumidor</button>\n");
      out.write("                    </div>\n");
      out.write(" \n");
      out.write(" \n");
      out.write("                    <div class=\"modal-footer\">\n");
      out.write("                        <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Cerrar</button>\n");
      out.write("                    </div>\n");
      out.write(" \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!------------------------------------------------------MODAL DE REGISTRO DE PROFESIONAL------------------------------------------------------------------------>\n");
      out.write("        <div class=\"modal fade\" id=\"formularioProfesional\" tabindex=\"-1\"\n");
      out.write("            role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header text-center\">\n");
      out.write("                        <h4 class=\"modal-title w-100 font-weight-bold\">Registrarse\n");
      out.write("                            como vendedor</h4>\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("                            aria-label=\"Close\">\n");
      out.write("                            <span aria-hidden=\"true\">&times;</span>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                    <form action=\"Principal\" method=\"post\">\n");
      out.write("                        <div class=\"modal-body mx-3\">\n");
      out.write("                            <div class=\"md-form mb-5\">\n");
      out.write("                                <i class=\"fas fa-user prefix grey-text\"></i> <input type=\"text\"\n");
      out.write("                                    id=\"orangeForm-name\" class=\"form-control validate\"\n");
      out.write("                                    name=\"nombrep\"> <label data-error=\"wrong\"\n");
      out.write("                                    data-success=\"right\" for=\"orangeForm-name\">Su nombre</label>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"md-form mb-5\">\n");
      out.write("                                <i class=\"fas fa-envelope prefix grey-text\"></i> <input\n");
      out.write("                                    type=\"email\" id=\"orangeForm-email\"\n");
      out.write("                                    class=\"form-control validate\" name=\"emailp\"> <label\n");
      out.write("                                    data-error=\"wrong\" data-success=\"right\" for=\"orangeForm-email\">Su\n");
      out.write("                                    email</label>\n");
      out.write("                            </div>\n");
      out.write(" \n");
      out.write("                            <div class=\"row my-5\">\n");
      out.write("                                <div class=\"col-md-4\">\n");
      out.write("                                    <div class=\"md-form\">\n");
      out.write("                                        <i class=\"fas fa-lock prefix\"></i> <input type=\"password\"\n");
      out.write("                                            id=\"inputValidationEx2\" class=\"form-control validate\"\n");
      out.write("                                            name=\"passwordp\"> <label for=\"inputValidationEx2\"\n");
      out.write("                                            data-error=\"Escriba su contraseña correctamente\"\n");
      out.write("                                            data-success=\"OK\" style=\"width: 200px;\">Password</label>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-md-5\">\n");
      out.write(" \n");
      out.write("                                    <div class=\"alert alert-warning password-alert\" role=\"alert\">\n");
      out.write("                                        <ul>\n");
      out.write("                                            <li class=\"requirements leng\"><i\n");
      out.write("                                                class=\"fas fa-check green-text\"></i><i\n");
      out.write("                                                class=\"fas fa-times red-text\"></i> 8 caracteres</li>\n");
      out.write("                                            <li class=\"requirements big-letter\"><i\n");
      out.write("                                                class=\"fas fa-check green-text\"></i><i\n");
      out.write("                                                class=\"fas fa-times red-text\"></i> 1 letra mayúscula</li>\n");
      out.write("                                            <li class=\"requirements num\"><i\n");
      out.write("                                                class=\"fas fa-check green-text\"></i><i\n");
      out.write("                                                class=\"fas fa-times red-text\"></i> 1 número</li>\n");
      out.write("                                            <li class=\"requirements special-char\"><i\n");
      out.write("                                                class=\"fas fa-check green-text\"></i><i\n");
      out.write("                                                class=\"fas fa-times red-text\"></i> 1 carácter especial</li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write(" \n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write(" \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"modal-footer d-flex justify-content-center\">\n");
      out.write("                            <button id=\"registrarse\" type=\"submit\"\n");
      out.write("                                class=\"btn btn-deep-orange\" disabled>Registrarse</button>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!------------------------------------------------------MODAL DE REGISTRO DE CLIENTE------------------------------------------------------------------------>\n");
      out.write("        <div class=\"modal fade\" id=\"formularioConsumidor\" tabindex=\"-1\"\n");
      out.write("            role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header text-center\">\n");
      out.write("                        <h4 class=\"modal-title w-100 font-weight-bold\">Registrarse\n");
      out.write("                            como cliente</h4>\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("                            aria-label=\"Close\">\n");
      out.write("                            <span aria-hidden=\"true\">&times;</span>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                    <form action=\"Principal\" method=\"post\">\n");
      out.write("                        <div class=\"modal-body mx-3\">\n");
      out.write("                            <div class=\"md-form mb-5\">\n");
      out.write("                                <i class=\"fas fa-user prefix grey-text\"></i> <input type=\"text\"\n");
      out.write("                                    id=\"orangeForm-name2\" class=\"form-control validate\"\n");
      out.write("                                    name=\"nombrec\"> <label data-error=\"wrong\"\n");
      out.write("                                    data-success=\"right\" for=\"orangeForm-name2\">Su nombre</label>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"md-form mb-5\">\n");
      out.write("                                <i class=\"fas fa-envelope prefix grey-text\"></i> <input\n");
      out.write("                                    type=\"email\" id=\"orangeForm-email2\"\n");
      out.write("                                    class=\"form-control validate\" name=\"emailc\"> <label\n");
      out.write("                                    data-error=\"wrong\" data-success=\"right\" for=\"orangeForm-email2\">Su\n");
      out.write("                                    email</label>\n");
      out.write("                            </div>\n");
      out.write(" \n");
      out.write("                            <div class=\"row my-5\">\n");
      out.write("                                <div class=\"col-md-4\">\n");
      out.write("                                    <div class=\"md-form\">\n");
      out.write("                                        <i class=\"fas fa-lock prefix\"></i> <input type=\"password\"\n");
      out.write("                                            id=\"inputValidationEx3\" class=\"form-control validate\"\n");
      out.write("                                            name=\"passwordc\"> <label for=\"inputValidationEx3\"\n");
      out.write("                                            data-error=\"Escriba su contraseña correctamente\"\n");
      out.write("                                            data-success=\"OK\" style=\"width: 200px;\">Password</label>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-md-5\">\n");
      out.write(" \n");
      out.write("                                    <div class=\"alert alert-warning password-alert\" role=\"alert\">\n");
      out.write("                                        <ul>\n");
      out.write("                                            <li class=\"requirements leng\"><i\n");
      out.write("                                                class=\"fas fa-check green-text\"></i><i\n");
      out.write("                                                class=\"fas fa-times red-text\"></i> 8 caracteres</li>\n");
      out.write("                                            <li class=\"requirements big-letter\"><i\n");
      out.write("                                                class=\"fas fa-check green-text\"></i><i\n");
      out.write("                                                class=\"fas fa-times red-text\"></i> 1 letra mayúscula</li>\n");
      out.write("                                            <li class=\"requirements num\"><i\n");
      out.write("                                                class=\"fas fa-check green-text\"></i><i\n");
      out.write("                                                class=\"fas fa-times red-text\"></i> 1 número</li>\n");
      out.write("                                            <li class=\"requirements special-char\"><i\n");
      out.write("                                                class=\"fas fa-check green-text\"></i><i\n");
      out.write("                                                class=\"fas fa-times red-text\"></i> 1 carácter especial</li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write(" \n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write(" \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"modal-footer d-flex justify-content-center\">\n");
      out.write("                            <button id=\"registrarse2\" type=\"submit\"\n");
      out.write("                                class=\"btn btn-deep-orange\" disabled>Registrarse</button>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!------------------------------------------------------ MODAL DE LOGIN ------------------------------------------------------------------------------------------->\n");
      out.write(" \n");
      out.write("        <div class=\"modal fade\" id=\"modalLogin\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("            aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header text-center\">\n");
      out.write("                        <h4 class=\"modal-title w-100 font-weight-bold\">ENTRAR</h4>\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("                            aria-label=\"Close\">\n");
      out.write("                            <span aria-hidden=\"true\">&times;</span>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                    <form action=\"Login\" method=\"post\">\n");
      out.write("                        <div class=\"modal-body mx-3\">\n");
      out.write(" \n");
      out.write("                            <div class=\"md-form mb-5\">\n");
      out.write("                                <i class=\"fas fa-envelope prefix grey-text\"></i> <input\n");
      out.write("                                    type=\"email\" id=\"defaultForm-email\"\n");
      out.write("                                    class=\"form-control validate\" name=\"email\"> <label\n");
      out.write("                                    data-error=\"wrong\" data-success=\"right\" for=\"defaultForm-email\">Email</label>\n");
      out.write("                            </div>\n");
      out.write(" \n");
      out.write("                            <div class=\"md-form mb-4\">\n");
      out.write("                                <i class=\"fas fa-lock prefix grey-text\"></i> <input\n");
      out.write("                                    type=\"password\" id=\"defaultForm-pass\"\n");
      out.write("                                    class=\"form-control validate\" name=\"password\"> <label\n");
      out.write("                                    data-error=\"wrong\" data-success=\"right\" for=\"defaultForm-pass\">Password</label>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"modal-footer d-flex justify-content-center\">\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-default\">Login</button>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write(" \n");
      out.write(" \n");
      out.write("    </div>\n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer class=\"page-footer font-small unique-color-dark pt-4\">\n");
      out.write(" \n");
      out.write("        <!-- Footer Elements -->\n");
      out.write("        <div class=\"container\">\n");
      out.write(" \n");
      out.write("            <!-- Call to action -->\n");
      out.write("            <ul class=\"list-unstyled list-inline text-center py-2\">\n");
      out.write("                <li class=\"list-inline-item\">\n");
      out.write("                    <h5 class=\"mb-1\">Regístrate gratis!</h5>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"list-inline-item\"><a href=\"Login\"\n");
      out.write("                    class=\"btn btn-outline-white btn-rounded\" data-toggle=\"modal\"\n");
      out.write("                    data-target=\"#modalRegistro\">Darse de alta</a></li>\n");
      out.write("            </ul>\n");
      out.write("            <!-- Call to action -->\n");
      out.write(" \n");
      out.write("        </div>\n");
      out.write("        <!-- Footer Elements -->\n");
      out.write(" \n");
      out.write("        <!-- Copyright -->\n");
      out.write("        <div class=\"footer-copyright text-center py-3 \">\n");
      out.write("            © 2020 Copyright: <a href=\"https://fetaqui.com/\"> fetaqui.com</a>\n");
      out.write("        </div>\n");
      out.write("        <!-- Copyright -->\n");
      out.write(" \n");
      out.write("    </footer>\n");
      out.write("    <!-- Footer -->\n");
      out.write(" \n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        function submit() {\n");
      out.write(" \n");
      out.write("            $('#categorias').submit();\n");
      out.write(" \n");
      out.write("        }\n");
      out.write(" \n");
      out.write("        $(function() {\n");
      out.write("            $('#selectCategorias').on('change', function() {\n");
      out.write("                submit();\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write(" \n");
      out.write(" \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
